Metrics/LineLength:
  Max: 130

Metrics/MethodLength:
  Max: 20

Style/MixinUsage:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false
