Metrics/LineLength:
  Max: 130

Style/Documentation:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enalbed: false
